name: login_repository
description: A repository that manages the login domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  build_runner: ^2.2.0
  hive_generator: ^1.1.3
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
