name: auth_repository
description: A repository that manages the authentication domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
